### ISSUE TITLE
Problema sulla Porta 8005

### ISSUE THREAD

**Issue by robertopinotti** [italia/spid-cie-oidc-php#25]
La guida dice di inserire questo codice dentro il docker-compose.yml
```
relying-party-drupal.org:
    image: linfaservice/spid-cie-oidc-php-drupal
    expose:
      - 8005
    ports:
      - "8005:8005"
    networks:
      - oidcfed
```
Però all'interno del docker-compose.yml c'è già questo pezzo di codice
```
wallet.trust-anchor.org:
    image: ghcr.io/italia/spid-cie-oidc-django:latest
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - ./examples-docker/wallet_trust_anchor:/django-project
    networks:
      - oidcfed
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/ta-ec.json &&
        python3 manage.py runserver 0.0.0.0:8005"
```
Entrambi quindi puntano alla porta 8005, questo crea un conflitto. E infatti quando da Terminale lancio il comando docker compose up mi dà questo errore
`Error response from daemon: driver failed programming external connectivity on endpoint spid-cie-oidc-django-main-wallet.trust-anchor.org-1 (...): Bind for 0.0.0.0:8005 failed: port is already allocated`
